    title: "Мой статический сайт"
    description: "Современный статический сайт на GitHub Pages"
    baseurl: "/test-static-site"
    url: "https://devalco.github.io"
    # Настройки сборки
    markdown: kramdown
    permalink: pretty
    # Плагины (если будем использовать Jekyll)
    plugins:
        - jekyll-sitemap
        - jekyll-seo-tag
    # SEO настройки
    google_analytics: false
    # Автор
    author:
        name: "Щевьев Алексей"
        email: "alcodevil@gmil.com"